module.exports = {
  DEFAULT_COLOR: "#0099ff",
  ERROR_COLOR: "#FF0000",
  SUCCESS_COLOR: "#00FF00",
  COMMAND_FOLDERS: ["moderacion", "utility", "api"],
  DEFAULT_COOLDOWN: 3, // Default cooldown in seconds
  COMMAND_COOLDOWNS: {
    ban: 10,
    kick: 10,
    say: 5,
    traducir: 5,
    servidor: 1,
  },
  banderas: {
    es: "🇪🇸",
    en: "🇺🇸",
    fr: "🇫🇷",
    de: "🇩🇪",
    it: "🇮🇹",
    pt: "🇵🇹",
    ja: "🇯🇵",
    zh: "🇨🇳",
    ru: "🇷🇺",
    ko: "🇰🇷",
    tr: "🇹🇷",
    pl: "🇵🇱",
    nl: "🇳🇱",
    sv: "🇸🇪",
    no: "🇳🇴",
    da: "🇩🇰",
    fi: "🇫🇮",
    el: "🇬🇷",
    hu: "🇭🇺",
    cs: "🇨🇿",
    ro: "🇷🇴",
    bg: "🇧🇬",
    hr: "🇭🇷",
    sk: "🇸🇰",
    sl: "🇸🇮",
    spa: "🇪🇸",
    eng: "🇺🇸",
    fra: "🇫🇷",
    deu: "🇩🇪",
    ita: "🇮🇹",
    por: "🇵🇹",
    jpn: "🇯🇵",
    zho: "🇨🇳",
    rus: "🇷🇺",
    kor: "🇰🇷",
    tur: "🇹🇷",
    pol: "🇵🇱",
    nld: "🇳🇱",
    swe: "🇸🇪",
    nor: "🇳🇴",
    dan: "🇩🇰",
    fin: "🇫🇮",
    ell: "🇬🇷",
    hun: "🇭🇺",
    ces: "🇨🇿",
    ron: "🇷🇴",
    bul: "🇧🇬",
    hrv: "🇭🇷",
    slk: "🇸🇰",
    slv: "🇸🇮",
  },
};
